config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'restaurants#index'

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]

  has_many :reviews, dependent: :destroy

  validates :name, presence: { message: "The restaurant must have a name" }
  validates :address, presence: { message: "The restaurant must have an address" }
  validates :category, inclusion: { in: CATEGORY, allow_nil: false, message: "The restaurant must have a category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0,1,2,3,3,4,5], allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]

  before_action :find_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @category = CATEGORY
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_restaurant, only: [ :new, :create ]

  def create
    @review = @restaurant.reviews.new(reviews_params)
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :template => 'restaurants/show'
    end
  end

  private

  def reviews_params
    params.require(:review).permit(:content, :rating)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title).blank? ? "RestoCool" : yield(:title) %> | RestoCool</title>
    <%= csrf_meta_tags %>

    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification message: 'Please fill all the fields below' %>

  <%= f.input :name, placeholder: "Chez Michel" %>
  <%= f.input :address, placeholder: "1 place de la bouffe" %>
  <%= f.input :category, collection: @category, prompt: "Select" %>
  <%= f.input :phone_number, placeholder: "06 XX XX XX XX" %>

  <%= f.button :submit %>
<% end %>

app/views/restaurants/_review_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.error_notification %>

  <div><strong>Rating<strong></div>
  <%= f.input :rating, collection: 0..5, as: :radio_buttons, label: false, item_label_class: "radio-inline", item_wrapper_tag: false %>
  <%= f.input :content, as: :text %>

  <%= f.button :submit %>
<% end %>

app/views/restaurants/index.html.erb
<% content_for :title do %>
  <%= "Restaurant list" %>
<% end %>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>Restaurants</h1>

    <div class="list-group">
      <% @restaurants.each do |restaurant| %>
        <%= link_to restaurant_path(restaurant), {class: "list-group-item"} do %>
          <strong><%= restaurant.name %></strong>
          <small> | <%= restaurant.category %></small>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

app/views/restaurants/new.html.erb
<% content_for :title do %>
  <%= "New restaurant" %>
<% end %>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">

    <h1>New restaurant</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/restaurants/show.html.erb
<% content_for :title do %>
  <%= @restaurant.name %>
<% end %>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">

    <h1><%= @restaurant.name %></h1>

    <p><i class="fa fa-cutlery" aria-hidden="true"></i>  <%= @restaurant.category %></p>
    <p><i class="fa fa-map-marker" aria-hidden="true"></i>  <%= @restaurant.address %></p>
    <p><i class="fa fa-phone" aria-hidden="true"></i>  <%= @restaurant.phone_number %></p>

    <h2>Reviews</h2>

    <% @restaurant.reviews.each do |review| %>
      <div class="row">
        <div class="col-xs-3">
          <% unless review.rating.nil? %>
            <% (review.rating).times do %>
              <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
            <% (5 - review.rating).times do %>
              <i class="fa fa-star-o" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </div>
        <div class="col-xs-9">
          <%= review.content %>
        </div>
      </div>
      <hr>
    <% end %>

    <div>
      <h3>Add a review</h3>
      <%= render 'reviews/form' %>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.error_notification message: 'Please fill all the fields below' %>

  <%= f.input :rating, collection: 0..5, as: :radio_buttons, label: false, item_label_class: "radio-inline", item_wrapper_tag: false %>
  <%= f.input :content, as: :text, placeholder: "Type your comment here" %>

  <%= f.button :submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path do %>
    <button class="btn btn-default btn-lg">
      <i class="fa fa-cutlery" aria-hidden="true"></i>  <span>Restaurant list</span>
    </button>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "New restaurant", new_restaurant_path, class: "navbar-wagon-item navbar-wagon-button btn"  %>

  </div>
</div>